{
 "title": "Service Health Baseline",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request rate per service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service_name) (\r\nrate(traces_span_metrics_calls_total{job=~\"otel-demo/.*\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate per service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service_name) (\r\nrate(traces_span_metrics_calls_total{status_code=\"STATUS_CODE_ERROR\"}[5m])\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "  sum by (service_name) (\r\n    rate(\r\n      traces_span_metrics_calls_total{\r\n        status_code=\"STATUS_CODE_ERROR\"\r\n      }[10m]\r\n    )\r\n  )  /\r\n  sum by (service_name) (\r\n    rate(\r\n      traces_span_metrics_calls_total{\r\n        job=~\"otel-demo/.\"\r\n      }[10m]\r\n    )\r\n  )\r\n * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 latency per service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\n  sum by (service_name, le) (\r\n    rate(traces_span_metrics_duration_milliseconds_bucket{\r\n     job=~\"otel-demo/.*\"\r\n    }[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}