apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yasmineelhakem/resilience-platform.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true # delete resources that are no longer defined in git
      selfHeal: true  # dont allow manual changes
    syncOptions:
      - CreateNamespace=true  # create the namespace if it doesn't exist