# Documentation: https://chaos-mesh.org/docs/run-a-chaos-experiment/
# Inject 500 ms latency into traffic from the frontend to the productcatalogservice

apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay
  namespace: chaos-mesh
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - otel-demo
    labelSelectors:
      app.kubernetes.io/name: frontend
  direction: to
  target:
    mode: all
    selector:
      namespaces:
        - otel-demo
      labelSelectors:
        app.kubernetes.io/name: product-catalog
  delay:
    latency: "500ms"
    correlation: "100"
    jitter: "0ms"