# Documentation: https://chaos-mesh.org/docs/simulate-heavy-stress-on-kubernetes/
# Simulate a frontend service under heavy memory load

apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: frontend-memory-stress
  namespace: chaos-mesh
spec:
  mode: one
  selector:
    namespaces:
      - otel-demo
    labelSelectors:
      app.kubernetes.io/name: frontend
  stressors:
    memory:
      workers: 1
      size: "512MB"
  duration: "2m"