{
 "title": "Chaos Experiment Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Cart Pod Kill", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cart PodLifecycle",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"otel-demo\", pod=~\"cart-.*\", phase=\"Running\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_status_phase{namespace=\"otel-demo\", pod=~\"cart-.*\", phase!=\"!Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Kill Experiment ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{service_name=\"cart\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cart p99 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"cart\"}[5m])) by (le)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dependency Failure Experiment (Payment Pod Kill)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Payment Pod Lifecycle",
   "type": "state-timeline",
   "description": "Payment Pod Kill Effect On Checkout",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"otel-demo\", pod=~\"payment-.*\", phase=\"Running\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_status_phase{namespace=\"otel-demo\", pod=~\"payment-.*\", phase!=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkout call rate + payment call rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{service_name=\"checkout\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{service_name=\"payment\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkout p99 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"checkout\", span_name=\"oteldemo.PaymentService/Charge\"}[2m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{service_name=\"checkout\", status_code=\"STATUS_CODE_UNSET\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network Delay ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "P99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"frontend\", span_name=\"oteldemo.ProductCatalogService/GetProduct\"}[2m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p50 / p95 / p99 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le) (\r\n    rate(\r\n      traces_span_metrics_duration_milliseconds_bucket{\r\n        service_name=\"frontend\",\r\n        span_name=\"oteldemo.ProductCatalogService/GetProduct\"\r\n      }[2m]\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(\r\n      traces_span_metrics_duration_milliseconds_bucket{\r\n        service_name=\"frontend\",\r\n        span_name=\"oteldemo.ProductCatalogService/GetProduct\"\r\n      }[2m]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le) (\r\n    rate(\r\n      traces_span_metrics_duration_milliseconds_bucket{\r\n        service_name=\"frontend\",\r\n        span_name=\"oteldemo.ProductCatalogService/GetProduct\"\r\n      }[2m]\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}