# Dependency failure experiment
# simulate payment Service unavailability to evaluate checkout Service resilience.
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: payment-pod-kill
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one
  duration: '2m'
  selector:
    namespaces:
      - otel-demo
    labelSelectors:
      'app.kubernetes.io/component': payment